### ISSUE TITLE
Erreur Compilation

### ISSUE THREAD

**Issue by dieg013** [chrisribe/ti-firebase#19] opened 2017-04-08 22:36 UTC
Hello, I tried to install the module but I have this error, I use the latest version of the SDK appcelerator 6.0.3.GA, you have a solution, thanks in advance :)

`[INFO] :   Invoking xcodebuild
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Products/Debug-iphonesimulator/myApp.app/myApp normal x86_64
[ERROR] :  (1 failure)`

**Comment by chrisribe** [comment] 2017-04-08 23:54
Bonjour / Hi,

Can you try version 1.2.0 to see if the crash occurs under that version ?
See this url for the 1.2.0 master state (there is a compiled zip in the root).
https://github.com/chrisribe/ti-firebase/tree/1830c1a952c550363a34a9c227d7df8048306553

I am wondering if the refactor in 1.3.0 could be the cause... @hansemannn ?
Christian

**Comment by hansemannn** [comment] 2017-04-09 13:15
Could be! Can you paste the full trace-log? The real error is shown before.

**Comment by dieg013** [comment] 2017-04-09 15:32
I created a new project to try me module but I have the error to compile, I have the error with the version of module 1.2.0 and 1.3.0. Does it work for you?

`[INFO] :   Creating assets image set
[INFO] :   Processing JavaScript files
[INFO] :   Writing app properties
[INFO] :   Writing i18n files
[INFO] :   Processing Titanium symbols
[INFO] :   Removing files
[INFO] :   Invoking xcodebuild
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Products/Debug-iphonesimulator/MyApp.app/MyApp normal x86_64
[ERROR] :  (1 failure)
`

**Comment by hansemannn** [comment] 2017-04-09 16:24
Ok, then it's unrelated to my recent PR. But as said above, we either need the full trace log (not just the error itself) to determine the real issue.

**Comment by dieg013** [comment] 2017-04-09 16:36
Can you try to create a new project and compile with the module you will see the same problem, thank

**Comment by hansemannn** [comment] 2017-04-09 16:44
Sorry, no resources for that right now.

**Comment by chrisribe** [comment] 2017-04-09 18:13
Will try recompiling when I get a chance. Maybe this afternoon or tomorrow...

**Comment by chrisribe** [comment] 2017-04-10 13:37
I have recompiled and 1.3 is crashing....

========
INFO] :   Removing files
[INFO] :   Invoking xcodebuild
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Intermediates/ti.fire.demo.build/Debug-iphonesimulator/ti.fire.demo.build/Objects-normal/i386/ti.fire.demo normal i386
[ERROR] :  	Ld build/Intermediates/ti.fire.demo.build/Debug-iphonesimulator/ti.fire.demo.build/Objects-normal/x86_64/ti.fire.demo normal x86_64
[ERROR] :  (2 failures)

====
If seems that some framework libraries where removed with the new firebase sdk but where not removed from the module.xcconfig. This was causing build issues on the Xcode side.

Offending includes:
-framework GoogleInterchangeUtilities -framework GoogleSymbolUtilities

### Quick tip ### 
If you want more details on module errors or other. You can build your project directly in Xcode it will show you the exact error and where to go from there.

I have recompiled + retested via the example code + insured that the firebase console does log the events.

Sorry for the issues, I assumed that the 1.3.0 was compiled and tested with a test project. 
I was short on time / lazy and did not test the pull request... Lesson learned.

Chris

**Comment by hansemannn** [comment] 2017-04-10 14:02
Yeah, I tested from Xcode as well, that's why it wasn't caught before. Sorry for the trouble!

**Comment by dieg013** [comment] 2017-04-10 14:05
Hi thanks for your quick replies I just tried version 1.3.1 here is the error at compilation

`
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:

[ERROR] :  	Ld build/Intermediates/MyApp.build/Debug-iphoneos/MyApp.build

/Objects-normal/armv7/MyApp normal armv7
[ERROR] :  	Ld build/Intermediates/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/MyApp normal arm64
[ERROR] :  (2 failures)`

**Comment by chrisribe** [comment] 2017-04-10 14:52
No problem @hansemannn this stuff happens, just happy it was an easy fix ;)

---
@dieg013 have you:
1. Cleaned your project ?
2. Selected the latest version in your ti.app (1.3.1) ?
3. Updated appcelerator to the latest SDK ?

If yes could you open your project in xcode, build it and paste the error message here ?
(double click file in build/iphone/<yourproject>.xcodeproj)

Thanks

**Comment by dieg013** [comment] 2017-04-12 22:51
Here is the error with xcode -> 
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by hansemannn** [comment] 2017-04-13 08:16
@dieg013 One more time....Either you provide the full error log (not just the part where it says there is an error) or we are not able to help out.

**Comment by chrisribe** [comment] 2017-04-13 14:18
I agree with @hansemannn  we need more than just the line with the error message.
Please provide more....

**Comment by chrisribe** [comment] 2017-04-18 22:10
@dieg013 since I have no updates on this I am closing this issue. If you do come back with a more complete error log, please post it here and I will reopen the issue.

Chris

**Closed as completed by chrisribe** 2017-04-18 22:10 UTC
